# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [27]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?
import numpy as np
from timeit import default_timer as timer

print('Lista')
start = timer()
lista1 = (range(0, 1000000))
lista2 = []
for x in lista1:
    x = x*2
    lista2.append(x)
end = timer()
print(end - start)

print('array')
start = timer()
array1 = np.arange(1, 1000001, 1)
array2 = 2 * array1
end = timer()
print(end - start)

Lista
0.40136019451912547
array
0.007817263058330026


### Exercício 2

In [40]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0
array3 = np.arange(1,11,1)
print(array3)
print(array3.dtype)
print(array3.ndim)
array3[5:9] = 0
array3

[ 1  2  3  4  5  6  7  8  9 10]
int32
1


array([ 1,  2,  3,  4,  5,  0,  0,  0,  0, 10])

### Exercício 3

In [45]:
# Crie um array de 3 dimensões e imprima a dimensão 1 
listaArr = [[0,1,2],[3,4,5],[6,7,9999]]
vetorLista = np.array(listaArr)
vetorLista.ndim
vetorLista[0]

array([0, 1, 2])

### Exercício 4

In [53]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

lista2d = [['a', 'f', 'teste'], ['q', 'kkkkkkk', 'logo'], ['iuiui', 'vcvcvc', 'isso']]
vetor2d = np.array(lista2d)
vetor2d.ndim
print(vetor2d[2])
print(vetor2d[0:1:1:2])

SyntaxError: invalid syntax (<ipython-input-53-087978efa3aa>, line 9)

### Exercício 5

In [56]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
print(arr)
print('transposta')
mT = arr.transpose()
print(mT)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
transposta
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


### Exercício 6

In [85]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.

import pandas as pd
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

for x, y, c in zip(xarr, yarr, cond):
    print(x, y, c)
    
resultado = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
resultado

1.1 2.1 True
1.2 2.2 False
1.3 2.3 True
1.4 2.4 True
1.5 2.5 False


[1.1, 2.2, 1.3, 1.4, 2.5]

### Exercício 7

In [62]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B
array_A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

np.save('teste.npy', array_A)
np.load('teste.npy')

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

### Exercício 8

In [64]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])
obj2 = set(obj)
obj2

{'a', 'b', 'c', 'd'}

### Exercício 9

In [86]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
from pandas import DataFrame as df
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [87]:
data = resp.json()
data[0]['title']

'Update ecosystem.rst to include Pint'

### Exercício 10

In [76]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas
import sqlite3
import os
con = sqlite3.connect('escola.db')
cur = con.cursor()
sql_create = 'create table cursos '\
'(id integer primary key, '\
'titulo varchar(100), '\
'categoria varchar(140))'
cur.execute(sql_create)

In [78]:
sql_insert = 'insert into cursos values (?, ?, ?)'
recset = [(1000, 'Ciência de Dados', 'Data Science'),
          (1001, 'Big Data Fundamentos', 'Big Data'),
          (1002, 'Python Fundamentos', 'Análise de Dados')]
for rec in recset:
    cur.execute(sql_insert, rec)
con.commit()

IntegrityError: UNIQUE constraint failed: cursos.id

In [81]:
cursor = con.execute('select * from cursos')
rows = cursor.fetchall()
rows

[(1000, 'Ciência de Dados', 'Data Science'),
 (1001, 'Big Data Fundamentos', 'Big Data'),
 (1002, 'Python Fundamentos', 'Análise de Dados')]

In [82]:
cursor.description
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

id                titulo         categoria
0  1000      Ciência de Dados      Data Science
1  1001  Big Data Fundamentos          Big Data
2  1002    Python Fundamentos  Análise de Dados

# Fim

### Obrigado - Data Science Academy - <a href=http://facebook.com/dsacademy>facebook.com/dsacademybr</a>